language: node_js
node_js:
  - 'node'
  - 'lts/*'
sudo: false
cache:
  directories:
    - ~/.npm
install:
  - npm i
script:
  - node --version
  - npm --version
  - npm start -- --version
  - npm start -- --help
  - npm test
after_success:
  - npm run report
